### ISSUE TITLE
HTTP Code 500

### ISSUE THREAD

**Issue by cubesky** [cxchope/cxchope.github.com#2]
![image](https://user-images.githubusercontent.com/8038511/30121910-82a0e32c-935f-11e7-859e-2977c18da55d.png)

**Comment by kagurazakayashi** [comment]
檢查到PHP乾淨升級後配寘有問題，部分PHP挿件沒有加入，導致WP文章頁（不含WP頁面頁）主題部分崩潰，相册系統瀏覽頁崩潰。現時已經對這些問題進行了修復。謝謝告知。
